import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type ReportItem = {
  test_name: string;
  value_text: string | null;
  value_numeric: number | null;
  unit: string | null;
  flag: string | null;
};

type ReportPdfInput = {
  order_no: string;
  patient_name: string;
  generated_at_iso: string;
  items: ReportItem[];
};

export async function buildReportPdf(input: ReportPdfInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const { width, height } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let y = height - 48;

  page.drawRectangle({ x: 32, y: height - 98, width: width - 64, height: 56, color: rgb(0.10, 0.32, 0.75) });
  page.drawText("PathologyLab Pro - Diagnostic Report", { x: 44, y: height - 72, size: 16, font: fontBold, color: rgb(1, 1, 1) });

  y -= 82;
  page.drawText(`Order: ${input.order_no}`, { x: 40, y, size: 11, font: fontBold, color: rgb(0.12, 0.16, 0.22) });
  y -= 16;
  page.drawText(`Patient: ${input.patient_name}`, { x: 40, y, size: 11, font });
  y -= 16;
  page.drawText(`Generated: ${new Date(input.generated_at_iso).toLocaleString()}`, { x: 40, y, size: 10, font, color: rgb(0.30, 0.37, 0.45) });

  y -= 26;
  page.drawRectangle({ x: 40, y, width: width - 80, height: 22, color: rgb(0.92, 0.95, 1) });
  page.drawText("Test", { x: 48, y: y + 7, size: 10, font: fontBold });
  page.drawText("Value", { x: 250, y: y + 7, size: 10, font: fontBold });
  page.drawText("Unit", { x: 360, y: y + 7, size: 10, font: fontBold });
  page.drawText("Flag", { x: 450, y: y + 7, size: 10, font: fontBold });

  y -= 24;

  for (const item of input.items) {
    if (y < 72) break;

    const value = item.value_numeric != null ? String(item.value_numeric) : item.value_text ?? "-";
    const flag = item.flag ?? "-";

    page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 0.6, color: rgb(0.88, 0.91, 0.96) });
    y -= 14;

    page.drawText(item.test_name.slice(0, 34), { x: 48, y, size: 10, font, color: rgb(0.13, 0.19, 0.30) });
    page.drawText(value.slice(0, 20), { x: 250, y, size: 10, font });
    page.drawText((item.unit ?? "-").slice(0, 12), { x: 360, y, size: 10, font });
    page.drawText(flag.slice(0, 10), { x: 450, y, size: 10, font, color: flag === "critical" ? rgb(0.75, 0.13, 0.16) : rgb(0.13, 0.19, 0.30) });

    y -= 16;
  }

  page.drawText("Generated by PathologyLab Pro", { x: 40, y: 30, size: 9, font, color: rgb(0.45, 0.50, 0.58) });

  return pdf.save();
}
